# Generated by Django 3.1.5 on 2021-01-28 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photobook',
            name='image',
            field=models.ImageField(upload_to='images'),
        ),
    ]
