# Generated by Django 3.1.5 on 2021-01-30 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0002_auto_20210128_1512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photobook',
            name='caption',
            field=models.CharField(max_length=100),
        ),
    ]
