# Generated by Django 3.1.5 on 2021-01-30 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0003_auto_20210130_1113'),
    ]

    operations = [
        migrations.AddField(
            model_name='photobook',
            name='published_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
