# Generated by Django 3.1.5 on 2021-01-30 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0004_photobook_published_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photobook',
            name='published_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
