# Generated by Django 3.1.5 on 2021-01-30 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0005_auto_20210130_1836'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photobook',
            name='published_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
